# language: cpp

# matrix:
#   include:
#     - os: linux
#       addons:
#         apt:
#           sources:
#             - ubuntu-toolchain-r-test
#           packages:
#             - g++-6
#       env:
#         - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
#   - os: linux
#       addons:
#         apt:
#           sources:
#             - llvm-toolchain-trusty
#           packages:
#             - clang-5.0
#       env:
#         - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
#   - os: osx
#     osx_image: xcode8
#       env:
#         - MATRIX_EVAL="brew install gcc && CC=gcc-6 && CXX=g++-6"
#   - os: osx
#     osx_image: xcode8
#       env:
#         - MATRIX_EVAL="CC=clang && CXX=clang++"

# before_install:
#   - eval "${MATRIX_EVAL}"
#   - echo $LANG
#   - echo $LC_ALL
#   - cmake --version
#   - ${CXX} --version
#   - ninja --version

# before_script:
#script: rake ci


language: cpp
sudo: false

matrix:
  include:
    - os: linux
      compiler: clang
      addons: &clang38
        apt:
          sources: ['llvm-toolchain-precise-3.8', 'ubuntu-toolchain-r-test']
          packages: ['clang-3.8', 'libicu-dev', 'libboost-all-dev']
      env: COMPILER='clang++-3.8' BUILD_TYPE='Release'
    - os: linux
      compiler: gcc
      addons: &gcc6
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6', 'libicu-dev', 'libboost-all-dev']
      env: COMPILER='g++-6' BUILD_TYPE='Release'
    - os: osx
      osx_image: xcode7.3
      compiler: clang
      env: COMPILER='clang++' BUILD_TYPE='Release'

    - os: osx
      osx_image: xcode8
      compiler: clang
      env: COMPILER='clang++' BUILD_TYPE='Release'

install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.8/cmake-3.8.2-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    elif [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      which cmake || brew install cmake
    fi
before_script:
  - export CXX=${COMPILER}
  - cd ${TRAVIS_BUILD_DIR}
  - cmake -H. -BBuild -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DTESTING=YES
  - cd Build

script:
  - make -j 2
  - ctest -V -j 2

branches:
  only:
  - master
env:
  global:
  - LANG="en_US.UTF-8"


