version: 1.0.0.{build}-{branch}

branches:
  only:
    - master

os:
  - Visual Studio 2017

shallow_clone: true

configuration:
  - Debug
  - Release

before_build:
    - cmake -H. -BBuild

# build with MSBuild
build:
  project: Build\Ecmascript.sln      # path to Visual Studio solution or project
  parallel: true                        # enable MSBuild parallel builds
  verbosity: normal                     # MSBuild verbosity level {quiet|minimal|normal|detailed}

test_script:
  - cd Build
  - ctest -V -j 2 -C %CONFIGURATION%






build_script:
    - cd C:\projects
    - nuget install nupengl.core
    - dir /s /b
    - cd C:\projects\visionaray
    - mkdir build
    - cd build
    - cmake -G "Visual Studio 14 2015 Win64"
      -DBOOST_ROOT="%BOOST_ROOT%"
      -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR_WIN64%"
      -DBoost_USE_STATIC_LIBS="ON"
      -DGLEW_INCLUDE_DIR="C:\projects\nupengl.core.0.1.0.1\build\native\include"
      -DGLEW_LIBRARY="C:\projects\nupengl.core.0.1.0.1\build\native\lib\x64\glew32.lib"
      -DGLUT_INCLUDE_DIR="C:\projects\nupengl.core.0.1.0.1\build\native\include"
      -DGLUT_glut_LIBRARY="C:\projects\nupengl.core.0.1.0.1\build\native\lib\x64\freeglut.lib"
      -DVSNRAY_ENABLE_EXAMPLES=ON
      -DVSNRAY_ENABLE_COMPILE_FAILURE_TESTS=ON
      -DVSNRAY_ENABLE_UNITTESTS=ON
      ..
    - msbuild visionaray.sln