.TH "src/ast.cpp" 3 "Sun Apr 30 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ast.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'ast\&.h'\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <boost/algorithm/string\&.hpp>\fP
.br
\fC#include <boost/core/demangle\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBCallableVisitor< Callable >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBast\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBstd::string\fP \fBnormalize\fP (const \fBstd::string\fP &s)"
.br
.ti -1c
.RI "template<typename F > \fBCallableVisitor\fP< F > \fBmake_visitor\fP (F callback)"
.br
.ti -1c
.RI "\fBstd::string\fP \fBto_string\fP (const \fBast::Program\fP &program)"
.br
.ti -1c
.RI "void \fBast::accept\fP (const \fBProgram\fP &program, \fBVisitor\fP &&visitor)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<typename F > \fBCallableVisitor\fP<F> make_visitor (F callback)"

.SS "\fBstd::string\fP normalize (const \fBstd::string\fP & s)"

.SS "\fBstd::string\fP to_string (const \fBast::Program\fP & program)"

.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
