.TH "src/ast.h" 3 "Tue May 2 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ast.h
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <boost/optional\&.hpp>\fP
.br
\fC#include <boost/variant\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBNode\fP"
.br
.ti -1c
.RI "struct \fBList< T >\fP"
.br
.ti -1c
.RI "struct \fBVisitor\fP"
.br
.ti -1c
.RI "struct \fBExpression\fP"
.br
.ti -1c
.RI "struct \fBPrimaryExpression\fP"
.br
.ti -1c
.RI "struct \fBThis\fP"
.br
.ti -1c
.RI "struct \fBIdentifier\fP"
.br
.ti -1c
.RI "struct \fBLiteral\fP"
.br
.ti -1c
.RI "struct \fBNullLiteral\fP"
.br
.ti -1c
.RI "struct \fBBooleanLiteral\fP"
.br
.ti -1c
.RI "struct \fBNumericLiteral\fP"
.br
.ti -1c
.RI "struct \fBStringLiteral\fP"
.br
.ti -1c
.RI "struct \fBRegularExpressionLiteral\fP"
.br
.ti -1c
.RI "struct \fBPropertyName\fP"
.br
.ti -1c
.RI "struct \fBPropertyAssignment\fP"
.br
.ti -1c
.RI "struct \fBElision\fP"
.br
.ti -1c
.RI "struct \fBElementList\fP"
.br
.ti -1c
.RI "struct \fBArrayLiteral\fP"
.br
.ti -1c
.RI "struct \fBPropertyNameAndValueList\fP"
.br
.ti -1c
.RI "struct \fBObjectLiteral\fP"
.br
.ti -1c
.RI "struct \fBMemberExpression\fP"
.br
.ti -1c
.RI "struct \fBArgumentList\fP"
.br
.ti -1c
.RI "struct \fBArguments\fP"
.br
.ti -1c
.RI "struct \fBNewExpression\fP"
.br
.ti -1c
.RI "struct \fBCallExpression\fP"
.br
.ti -1c
.RI "struct \fBPostfixExpression\fP"
.br
.ti -1c
.RI "struct \fBUnaryExpression\fP"
.br
.ti -1c
.RI "struct \fBBinaryExpression\fP"
.br
.ti -1c
.RI "struct \fBConditionalExpression\fP"
.br
.ti -1c
.RI "struct \fBVariableDeclaration\fP"
.br
.ti -1c
.RI "struct \fBVariableDeclarationList\fP"
.br
.ti -1c
.RI "struct \fBSourceElement\fP"
.br
.ti -1c
.RI "struct \fBStatement\fP"
.br
.ti -1c
.RI "struct \fBStatementList\fP"
.br
.ti -1c
.RI "struct \fBBlock\fP"
.br
.ti -1c
.RI "struct \fBVariableStatement\fP"
.br
.ti -1c
.RI "struct \fBEmptyStatement\fP"
.br
.ti -1c
.RI "struct \fBExpressionStatement\fP"
.br
.ti -1c
.RI "struct \fBIfStatement\fP"
.br
.ti -1c
.RI "struct \fBDoWhileStatement\fP"
.br
.ti -1c
.RI "struct \fBWhileStatement\fP"
.br
.ti -1c
.RI "struct \fBForStatement\fP"
.br
.ti -1c
.RI "struct \fBForInStatement\fP"
.br
.ti -1c
.RI "struct \fBContinueStatement\fP"
.br
.ti -1c
.RI "struct \fBBreakStatement\fP"
.br
.ti -1c
.RI "struct \fBReturnStatement\fP"
.br
.ti -1c
.RI "struct \fBWithStatement\fP"
.br
.ti -1c
.RI "struct \fBLabelledStatement\fP"
.br
.ti -1c
.RI "struct \fBCaseClause\fP"
.br
.ti -1c
.RI "struct \fBDefaultClause\fP"
.br
.ti -1c
.RI "struct \fBCaseBlock\fP"
.br
.ti -1c
.RI "struct \fBSwitchStatement\fP"
.br
.ti -1c
.RI "struct \fBThrowStatement\fP"
.br
.ti -1c
.RI "struct \fBTryStatement\fP"
.br
.ti -1c
.RI "struct \fBDebuggerStatement\fP"
.br
.ti -1c
.RI "struct \fBDeclaration\fP"
.br
.ti -1c
.RI "struct \fBSourceElements\fP"
.br
.ti -1c
.RI "struct \fBFormalParameterList\fP"
.br
.ti -1c
.RI "struct \fBFunctionBody\fP"
.br
.ti -1c
.RI "struct \fBFunctionDeclaration\fP"
.br
.ti -1c
.RI "struct \fBFunctionExpression\fP"
.br
.ti -1c
.RI "struct \fBProgram\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBaccept\fP (const \fBProgram\fP &program, \fBVisitor\fP &&visitor)"
.br
.ti -1c
.RI "\fBstd::string\fP \fBto_string\fP (const \fBProgram\fP &program)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void accept (const \fBProgram\fP & program, \fBVisitor\fP && visitor)"

.SS "\fBstd::string\fP to_string (const \fBProgram\fP & program)"

.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
