.TH "ast::Statement" 3 "Sun Apr 30 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ast::Statement
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.PP
Inherits \fBast::SourceElement\fP\&.
.PP
Inherited by \fBast::Block\fP, \fBast::BreakStatement\fP, \fBast::ContinueStatement\fP, \fBast::DebuggerStatement\fP, \fBast::DoWhileStatement\fP, \fBast::EmptyStatement\fP, \fBast::ExpressionStatement\fP, \fBast::ForInStatement\fP, \fBast::ForStatement\fP, \fBast::IfStatement\fP, \fBast::LabelledStatement\fP, \fBast::ReturnStatement\fP, \fBast::SwitchStatement\fP, \fBast::ThrowStatement\fP, \fBast::TryStatement\fP, \fBast::VariableStatement\fP, \fBast::WhileStatement\fP, and \fBast::WithStatement\fP\&.
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
