.TH "ast::WithStatement" 3 "Mon May 1 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ast::WithStatement
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.PP
Inherits \fBast::Statement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWithStatement\fP (\fBExpression\fP *\fBobject\fP, \fBStatement\fP *\fBbody\fP)"
.br
.ti -1c
.RI "void \fBaccept\fP (\fBVisitor\fP &visitor) const override"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBExpression\fP * \fBobject\fP"
.br
.ti -1c
.RI "\fBStatement\fP * \fBbody\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ast::WithStatement::WithStatement (\fBExpression\fP * object, \fBStatement\fP * body)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void ast::WithStatement::accept (\fBVisitor\fP & visitor) const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBast::Node\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBStatement\fP* ast::WithStatement::body"

.SS "\fBExpression\fP* ast::WithStatement::object"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
