.TH "ast::Literal" 3 "Sun Apr 30 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ast::Literal
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.PP
Inherits \fBast::PrimaryExpression\fP\&.
.PP
Inherited by \fBast::BooleanLiteral\fP, \fBast::NullLiteral\fP, \fBast::NumericLiteral\fP, \fBast::RegularExpressionLiteral\fP, and \fBast::StringLiteral\fP\&.
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
