.TH "ast::PrimaryExpression" 3 "Sun Apr 30 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ast::PrimaryExpression
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.PP
Inherits \fBast::Expression\fP\&.
.PP
Inherited by \fBast::ArrayLiteral\fP, \fBast::Identifier\fP, \fBast::Literal\fP, \fBast::ObjectLiteral\fP, and \fBast::This\fP\&.
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
