.TH "ast::Arguments" 3 "Mon May 1 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ast::Arguments
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.PP
Inherits \fBast::Expression\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBArguments\fP (\fBArgumentList\fP *\fBlist\fP=nullptr)"
.br
.ti -1c
.RI "void \fBaccept\fP (\fBVisitor\fP &visitor) const override"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBArgumentList\fP * \fBlist\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ast::Arguments::Arguments (\fBArgumentList\fP * list = \fCnullptr\fP)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void ast::Arguments::accept (\fBVisitor\fP & visitor) const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBast::Node\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBArgumentList\fP* ast::Arguments::list"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
