.TH "ast::Program" 3 "Sun Apr 30 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ast::Program
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstd::shared_ptr\fP< void > \fBstorage\fP"
.br
.ti -1c
.RI "\fBSourceElements\fP * \fBbody\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBSourceElements\fP* ast::Program::body"

.SS "\fBstd::shared_ptr\fP<void> ast::Program::storage"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
