.TH "ast::Expression" 3 "Sun Apr 30 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ast::Expression
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.PP
Inherits \fBast::Node\fP\&.
.PP
Inherited by \fBast::Arguments\fP, \fBast::ArrayLiteral\fP, \fBast::BinaryExpression\fP, \fBast::BooleanLiteral\fP, \fBast::CallExpression\fP, \fBast::ConditionalExpression\fP, \fBast::Elision\fP, \fBast::FunctionExpression\fP, \fBast::Identifier\fP, \fBast::MemberExpression\fP, \fBast::NewExpression\fP, \fBast::NullLiteral\fP, \fBast::NumericLiteral\fP, \fBast::ObjectLiteral\fP, \fBast::PostfixExpression\fP, \fBast::PropertyAssignment\fP, \fBast::PropertyName\fP, \fBast::RegularExpressionLiteral\fP, \fBast::StringLiteral\fP, \fBast::This\fP, \fBast::UnaryExpression\fP, and \fBast::VariableDeclaration\fP\&.
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
