.TH "ast::Block" 3 "Mon May 1 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ast::Block
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.PP
Inherits \fBast::Statement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBlock\fP (\fBStatementList\fP *\fBbody\fP=nullptr)"
.br
.ti -1c
.RI "void \fBaccept\fP (\fBVisitor\fP &visitor) const override"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBStatementList\fP * \fBbody\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ast::Block::Block (\fBStatementList\fP * body = \fCnullptr\fP)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void ast::Block::accept (\fBVisitor\fP & visitor) const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBast::Node\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBStatementList\fP* ast::Block::body"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
