.TH "ast::FunctionBody" 3 "Mon May 1 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ast::FunctionBody
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.PP
Inherits \fBast::SourceElements\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFunctionBody\fP (\fBSourceElements\fP *body=nullptr)"
.br
.ti -1c
.RI "void \fBaccept\fP (\fBVisitor\fP &visitor) const override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ast::FunctionBody::FunctionBody (\fBSourceElements\fP * body = \fCnullptr\fP)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void ast::FunctionBody::accept (\fBVisitor\fP & visitor) const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBast::Node\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
