.TH "ast::MemberExpression" 3 "Mon May 1 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ast::MemberExpression
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.PP
Inherits \fBast::Expression\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMemberExpression\fP (\fBExpression\fP *\fBobject\fP, \fBExpression\fP *\fBproperty\fP)"
.br
.ti -1c
.RI "void \fBaccept\fP (\fBVisitor\fP &visitor) const override"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBExpression\fP * \fBobject\fP"
.br
.ti -1c
.RI "\fBExpression\fP * \fBproperty\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ast::MemberExpression::MemberExpression (\fBExpression\fP * object, \fBExpression\fP * property)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void ast::MemberExpression::accept (\fBVisitor\fP & visitor) const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBast::Node\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBExpression\fP* ast::MemberExpression::object"

.SS "\fBExpression\fP* ast::MemberExpression::property"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
