.TH "BasicLexer< T >::Tokens::storage_t" 3 "Wed Jun 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BasicLexer< T >::Tokens::storage_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lexer\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstorage_t\fP ()"
.br
.ti -1c
.RI "\fBstorage_t\fP (\fBstd::vector\fP< \fBToken\fP > &&\fBtokens\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstd::vector\fP< \fBToken\fP > \fBtokens\fP"
.br
.ti -1c
.RI "\fBstd::vector\fP< \fBstd::unique_ptr\fP< DebugInfo > > \fBdebug_infos\fP"
.br
.ti -1c
.RI "\fBstd::vector\fP< \fBstd::unique_ptr\fP< \fBstd::u16string\fP > > \fBstrings\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T> \fBBasicLexer\fP< T >::Tokens::storage_t::storage_t ()\fC [inline]\fP"

.SS "template<typename T> \fBBasicLexer\fP< T >::Tokens::storage_t::storage_t (\fBstd::vector\fP< \fBToken\fP > && tokens)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<typename T> \fBstd::vector\fP<\fBstd::unique_ptr\fP<DebugInfo> > \fBBasicLexer\fP< T >::Tokens::storage_t::debug_infos"

.SS "template<typename T> \fBstd::vector\fP<\fBstd::unique_ptr\fP<\fBstd::u16string\fP> > \fBBasicLexer\fP< T >::Tokens::storage_t::strings"

.SS "template<typename T> \fBstd::vector\fP<\fBToken\fP> \fBBasicLexer\fP< T >::Tokens::storage_t::tokens"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
