.TH "src/basic_visitor.h" 3 "Tue May 30 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/basic_visitor.h
.SH SYNOPSIS
.br
.PP
\fC#include 'ast\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBBasicVisitor\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
