.TH "BasicParser" 3 "Sat Apr 29 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BasicParser
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <parser\&.h>\fP
.PP
Inherited by \fBExpressionParser\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename It > \fBBasicParser\fP (It begin, It end)"
.br
.ti -1c
.RI "bool \fBno_line_terminator_here\fP ()"
.br
.ti -1c
.RI "bool \fBautomatic_semicolon_insertion\fP ()"
.br
.ti -1c
.RI "bool \fBsyntax_error\fP (\fBstd::string\fP what={})"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBMatcher\fP< \fBToken\fP, \fBstd::vector\fP< \fBToken\fP >::iterator > \fBmatch\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename It > BasicParser::BasicParser (It begin, It end)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool BasicParser::automatic_semicolon_insertion ()\fC [inline]\fP"

.SS "bool BasicParser::no_line_terminator_here ()\fC [inline]\fP"

.SS "bool BasicParser::syntax_error (\fBstd::string\fP what = \fC{}\fP)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBMatcher\fP<\fBToken\fP, \fBstd::vector\fP<\fBToken\fP>::iterator> BasicParser::match\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
