.TH "BasicLexer< T >" 3 "Sun Apr 30 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BasicLexer< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lexer\&.h>\fP
.PP
Inherited by \fBStringConverter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBasicLexer\fP ()"
.br
.ti -1c
.RI "\fBBasicLexer\fP (\fBstd::initializer_list\fP< \fBToken\fP > \fBtokens\fP)"
.br
.ti -1c
.RI "template<typename It > \fBBasicLexer\fP (It begin, It end)"
.br
.ti -1c
.RI "\fBBasicLexer\fP (const \fBstd::u16string\fP &str)"
.br
.ti -1c
.RI "\fBBasicLexer\fP (const \fBstd::string\fP &str)"
.br
.ti -1c
.RI "const \fBstd::vector\fP< \fBToken\fP > & \fBtokens\fP () const"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T> \fBBasicLexer\fP< T >::\fBBasicLexer\fP ()\fC [inline]\fP"

.SS "template<typename T> \fBBasicLexer\fP< T >::\fBBasicLexer\fP (\fBstd::initializer_list\fP< \fBToken\fP > tokens)\fC [inline]\fP"

.SS "template<typename T> template<typename It > \fBBasicLexer\fP< T >::\fBBasicLexer\fP (It begin, It end)\fC [inline]\fP"

.SS "template<typename T> \fBBasicLexer\fP< T >::\fBBasicLexer\fP (const \fBstd::u16string\fP & str)\fC [inline]\fP"

.SS "template<typename T> \fBBasicLexer\fP< T >::\fBBasicLexer\fP (const \fBstd::string\fP & str)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename T> const \fBstd::vector\fP<\fBToken\fP>& \fBBasicLexer\fP< T >::tokens () const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
