.TH "BCinfo" 3 "Sat Jun 10 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BCinfo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBdp0\fP"
.br
.ti -1c
.RI "int \fBdp1\fP"
.br
.ti -1c
.RI "int \fBdplen\fP"
.br
.ti -1c
.RI "int \fBdsign\fP"
.br
.ti -1c
.RI "int \fBe0\fP"
.br
.ti -1c
.RI "int \fBinexact\fP"
.br
.ti -1c
.RI "int \fBnd\fP"
.br
.ti -1c
.RI "int \fBnd0\fP"
.br
.ti -1c
.RI "int \fBrounding\fP"
.br
.ti -1c
.RI "int \fBscale\fP"
.br
.ti -1c
.RI "int \fBuflchk\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int BCinfo::dp0"

.SS "int BCinfo::dp1"

.SS "int BCinfo::dplen"

.SS "int BCinfo::dsign"

.SS "int BCinfo::e0"

.SS "int BCinfo::inexact"

.SS "int BCinfo::nd"

.SS "int BCinfo::nd0"

.SS "int BCinfo::rounding"

.SS "int BCinfo::scale"

.SS "int BCinfo::uflchk"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
