.TH "BF96" 3 "Sat Jun 10 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BF96
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBb0\fP"
.br
.ti -1c
.RI "unsigned int \fBb1\fP"
.br
.ti -1c
.RI "unsigned int \fBb2\fP"
.br
.ti -1c
.RI "int \fBe\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "unsigned int BF96::b0"

.SS "unsigned int BF96::b1"

.SS "unsigned int BF96::b2"

.SS "int BF96::e"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
