.TH "Binding" 3 "Wed Jun 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Binding
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <runtime\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBType\fP \fBvalue\fP"
.br
.ti -1c
.RI "bool \fBis_deletable\fP = true"
.br
.ti -1c
.RI "bool \fBis_mutable\fP = true"
.br
.ti -1c
.RI "bool \fBis_initialized\fP = false"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "bool Binding::is_deletable = true"

.SS "bool Binding::is_initialized = false"

.SS "bool Binding::is_mutable = true"

.SS "\fBType\fP Binding::value"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
