.TH "Boolean" 3 "Tue May 30 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Boolean
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <types\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBvalue\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "bool Boolean::value"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
