.TH "BreakStatement" 3 "Tue May 2 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BreakStatement
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.PP
Inherits \fBStatement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBreakStatement\fP (\fBIdentifier\fP *\fBlabel\fP=nullptr)"
.br
.ti -1c
.RI "void \fBaccept\fP (\fBVisitor\fP &visitor) const override"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBIdentifier\fP * \fBlabel\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BreakStatement::BreakStatement (\fBIdentifier\fP * label = \fCnullptr\fP)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void BreakStatement::accept (\fBVisitor\fP & visitor) const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBNode\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBIdentifier\fP* BreakStatement::label"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
