.TH "BreakStatement" 3 "Sat Apr 29 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BreakStatement
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "boost::optional< \fBIdentifier\fP > \fBlabel\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "boost::optional<\fBIdentifier\fP> BreakStatement::label"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
