.TH "Builder< Node >" 3 "Sat Apr 29 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Builder< Node >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <parser\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBpush\fP (Node &&node)"
.br
.ti -1c
.RI "template<typename T , typename\&.\&.\&. Args> void \fBpush\fP (Args &&\&.\&.\&. args)"
.br
.ti -1c
.RI "template<typename T , std::size_t N> void \fBreplace\fP ()"
.br
.ti -1c
.RI "template<typename T , typename\&.\&.\&. Ts, typename\&.\&.\&. Args> void \fBreplace\fP (Args &&\&.\&.\&. args)"
.br
.ti -1c
.RI "Node \fBpop\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<typename Node> Node \fBBuilder\fP< Node >::pop ()\fC [inline]\fP"

.SS "template<typename Node> void \fBBuilder\fP< Node >::push (Node && node)\fC [inline]\fP"

.SS "template<typename Node> template<typename T , typename\&.\&.\&. Args> void \fBBuilder\fP< Node >::push (Args &&\&.\&.\&. args)\fC [inline]\fP"

.SS "template<typename Node> template<typename T , std::size_t N> void \fBBuilder\fP< Node >::replace ()\fC [inline]\fP"

.SS "template<typename Node> template<typename T , typename\&.\&.\&. Ts, typename\&.\&.\&. Args> void \fBBuilder\fP< Node >::replace (Args &&\&.\&.\&. args)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
