.TH "CaseClause" 3 "Sat Jun 10 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CaseClause
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.PP
Inherits \fBNode\fP\&.
.PP
Inherited by \fBDefaultClause\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCaseClause\fP (\fBExpression\fP *\fBtest\fP, \fBStatementList\fP *\fBconsequent\fP)"
.br
.ti -1c
.RI "void \fBaccept\fP (\fBVisitor\fP &visitor) const override"
.br
.ti -1c
.RI "const char * \fBtype\fP () const override"
.br
.ti -1c
.RI "bool \fBis_default\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBExpression\fP * \fBtest\fP = nullptr"
.br
.ti -1c
.RI "\fBStatementList\fP * \fBconsequent\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CaseClause::CaseClause (\fBExpression\fP * test, \fBStatementList\fP * consequent)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void CaseClause::accept (\fBVisitor\fP & visitor) const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBNode\fP\&.
.PP
Reimplemented in \fBDefaultClause\fP\&.
.SS "bool CaseClause::is_default () const\fC [inline]\fP"

.SS "const char* CaseClause::type () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBNode\fP\&.
.PP
Reimplemented in \fBDefaultClause\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBStatementList\fP* CaseClause::consequent"

.SS "\fBExpression\fP* CaseClause::test = nullptr"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
