.TH "Catch::SectionInfo" 3 "Wed Jun 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::SectionInfo
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <catch\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSectionInfo\fP (\fBSourceLineInfo\fP const &_lineInfo, \fBstd::string\fP const &_name, \fBstd::string\fP const &_description=\fBstd::string\fP())"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstd::string\fP \fBname\fP"
.br
.ti -1c
.RI "\fBstd::string\fP \fBdescription\fP"
.br
.ti -1c
.RI "\fBSourceLineInfo\fP \fBlineInfo\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Catch::SectionInfo::SectionInfo (\fBSourceLineInfo\fP const & _lineInfo, \fBstd::string\fP const & _name, \fBstd::string\fP const & _description = \fC\fBstd::string\fP()\fP)"

.SH "Member Data Documentation"
.PP 
.SS "\fBstd::string\fP Catch::SectionInfo::description"

.SS "\fBSourceLineInfo\fP Catch::SectionInfo::lineInfo"

.SS "\fBstd::string\fP Catch::SectionInfo::name"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
