.TH "Catch::SafeBool" 3 "Wed Jun 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::SafeBool
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <catch\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef void(SafeBool::* \fBtype\fP) () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBtype\fP \fBmakeSafe\fP (bool value)"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "typedef void(SafeBool::* Catch::SafeBool::type) () const"

.SH "Member Function Documentation"
.PP 
.SS "static \fBtype\fP Catch::SafeBool::makeSafe (bool value)\fC [inline]\fP, \fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
