.TH "Catch::Detail::TrueType" 3 "Wed Jun 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::Detail::TrueType
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <catch\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBsizer\fP [1]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "char Catch::Detail::TrueType::sizer[1]"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
