.TH "Catch::Matchers::StdString::ContainsMatcher" 3 "Wed Jun 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::Matchers::StdString::ContainsMatcher
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <catch\&.hpp>\fP
.PP
Inherits \fBCatch::Matchers::StdString::StringMatcherBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBContainsMatcher\fP (\fBCasedString\fP const &comparator)"
.br
.ti -1c
.RI "virtual bool \fBmatch\fP (\fBstd::string\fP const &source) const \fBCATCH_OVERRIDE\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Catch::Matchers::StdString::ContainsMatcher::ContainsMatcher (\fBCasedString\fP const & comparator)"

.SH "Member Function Documentation"
.PP 
.SS "virtual bool Catch::Matchers::StdString::ContainsMatcher::match (\fBstd::string\fP const & source) const\fC [virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
