.TH "Catch::NotImplementedException" 3 "Wed Jun 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::NotImplementedException
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <catch\&.hpp>\fP
.PP
Inherits \fBstd::exception\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNotImplementedException\fP (\fBSourceLineInfo\fP const &lineInfo)"
.br
.ti -1c
.RI "\fBNotImplementedException\fP (\fBNotImplementedException\fP const &)"
.br
.ti -1c
.RI "virtual \fB~NotImplementedException\fP () \fBCATCH_NOEXCEPT\fP"
.br
.ti -1c
.RI "virtual const char * \fBwhat\fP () const \fBCATCH_NOEXCEPT\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Catch::NotImplementedException::NotImplementedException (\fBSourceLineInfo\fP const & lineInfo)"

.SS "Catch::NotImplementedException::NotImplementedException (\fBNotImplementedException\fP const &)\fC [inline]\fP"

.SS "virtual Catch::NotImplementedException::~NotImplementedException ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual const char* Catch::NotImplementedException::what () const\fC [virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
