.TH "Catch::SharedImpl< T >" 3 "Wed Jun 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::SharedImpl< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <catch\&.hpp>\fP
.PP
Inherits T\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSharedImpl\fP ()"
.br
.ti -1c
.RI "virtual void \fBaddRef\fP () const"
.br
.ti -1c
.RI "virtual void \fBrelease\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBm_rc\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T = IShared> \fBCatch::SharedImpl\fP< T >::\fBSharedImpl\fP ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename T = IShared> virtual void \fBCatch::SharedImpl\fP< T >::addRef () const\fC [inline]\fP, \fC [virtual]\fP"

.SS "template<typename T = IShared> virtual void \fBCatch::SharedImpl\fP< T >::release () const\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<typename T = IShared> unsigned int \fBCatch::SharedImpl\fP< T >::m_rc\fC [mutable]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
