.TH "Catch::IMutableContext" 3 "Wed Jun 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::IMutableContext
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <catch\&.hpp>\fP
.PP
Inherits \fBCatch::IContext\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~IMutableContext\fP ()"
.br
.ti -1c
.RI "virtual void \fBsetResultCapture\fP (\fBIResultCapture\fP *resultCapture)=0"
.br
.ti -1c
.RI "virtual void \fBsetRunner\fP (\fBIRunner\fP *runner)=0"
.br
.ti -1c
.RI "virtual void \fBsetConfig\fP (\fBPtr\fP< IConfig const > const &config)=0"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual Catch::IMutableContext::~IMutableContext ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual void Catch::IMutableContext::setConfig (\fBPtr\fP< IConfig const > const & config)\fC [pure virtual]\fP"

.SS "virtual void Catch::IMutableContext::setResultCapture (\fBIResultCapture\fP * resultCapture)\fC [pure virtual]\fP"

.SS "virtual void Catch::IMutableContext::setRunner (\fBIRunner\fP * runner)\fC [pure virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
