.TH "Catch::SectionEndInfo" 3 "Wed Jun 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::SectionEndInfo
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <catch\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSectionEndInfo\fP (\fBSectionInfo\fP const &_sectionInfo, \fBCounts\fP const &_prevAssertions, double _durationInSeconds)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSectionInfo\fP \fBsectionInfo\fP"
.br
.ti -1c
.RI "\fBCounts\fP \fBprevAssertions\fP"
.br
.ti -1c
.RI "double \fBdurationInSeconds\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Catch::SectionEndInfo::SectionEndInfo (\fBSectionInfo\fP const & _sectionInfo, \fBCounts\fP const & _prevAssertions, double _durationInSeconds)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "double Catch::SectionEndInfo::durationInSeconds"

.SS "\fBCounts\fP Catch::SectionEndInfo::prevAssertions"

.SS "\fBSectionInfo\fP Catch::SectionEndInfo::sectionInfo"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
