.TH "Catch::Matchers::Impl" 3 "Wed Jun 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::Matchers::Impl
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBMatchAllOf\fP"
.br
.ti -1c
.RI "struct \fBMatchAnyOf\fP"
.br
.ti -1c
.RI "struct \fBMatcherBase\fP"
.br
.ti -1c
.RI "struct \fBMatcherMethod\fP"
.br
.ti -1c
.RI "struct \fBMatcherMethod< PtrT * >\fP"
.br
.ti -1c
.RI "class \fBMatcherUntypedBase\fP"
.br
.ti -1c
.RI "struct \fBMatchNotOf\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
