.TH "Catch::CaseSensitive" 3 "Wed Jun 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::CaseSensitive
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <catch\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBChoice\fP { \fBYes\fP, \fBNo\fP }"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBCatch::CaseSensitive::Choice\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIYes \fP\fP
.TP
\fB\fINo \fP\fP


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
