.TH "Catch::Section" 3 "Wed Jun 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::Section
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <catch\&.hpp>\fP
.PP
Inherits \fBCatch::NonCopyable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSection\fP (\fBSectionInfo\fP const &info)"
.br
.ti -1c
.RI "\fB~Section\fP ()"
.br
.ti -1c
.RI "\fBoperator bool\fP () const"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Catch::Section::Section (\fBSectionInfo\fP const & info)"

.SS "Catch::Section::~Section ()"

.SH "Member Function Documentation"
.PP 
.SS "Catch::Section::operator bool () const"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
