.TH "Catch::IGeneratorInfo" 3 "Wed Jun 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::IGeneratorInfo
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <catch\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~IGeneratorInfo\fP ()"
.br
.ti -1c
.RI "virtual bool \fBmoveNext\fP ()=0"
.br
.ti -1c
.RI "virtual \fBstd::size_t\fP \fBgetCurrentIndex\fP () const =0"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual Catch::IGeneratorInfo::~IGeneratorInfo ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual \fBstd::size_t\fP Catch::IGeneratorInfo::getCurrentIndex () const\fC [pure virtual]\fP"

.SS "virtual bool Catch::IGeneratorInfo::moveNext ()\fC [pure virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
