.TH "Catch::Matchers::Impl::MatchNotOf< ArgT >" 3 "Wed Jun 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::Matchers::Impl::MatchNotOf< ArgT >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <catch\&.hpp>\fP
.PP
Inherits \fBCatch::Matchers::Impl::MatcherBase< ArgT >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMatchNotOf\fP (\fBMatcherBase\fP< ArgT > const &underlyingMatcher)"
.br
.ti -1c
.RI "virtual bool \fBmatch\fP (ArgT const &arg) const \fBCATCH_OVERRIDE\fP"
.br
.ti -1c
.RI "virtual \fBstd::string\fP \fBdescribe\fP () const \fBCATCH_OVERRIDE\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMatcherBase\fP< ArgT > const  & \fBm_underlyingMatcher\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename ArgT> \fBCatch::Matchers::Impl::MatchNotOf\fP< ArgT >::\fBMatchNotOf\fP (\fBMatcherBase\fP< ArgT > const & underlyingMatcher)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename ArgT> virtual \fBstd::string\fP \fBCatch::Matchers::Impl::MatchNotOf\fP< ArgT >::describe () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBCatch::Matchers::Impl::MatcherUntypedBase\fP\&.
.SS "template<typename ArgT> virtual bool \fBCatch::Matchers::Impl::MatchNotOf\fP< ArgT >::match (ArgT const & arg) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBCatch::Matchers::Impl::MatcherMethod< ArgT >\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "template<typename ArgT> \fBMatcherBase\fP<ArgT> const& \fBCatch::Matchers::Impl::MatchNotOf\fP< ArgT >::m_underlyingMatcher"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
