.TH "Catch::Internal::OperatorTraits< Op >" 3 "Wed Jun 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::Internal::OperatorTraits< Op >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <catch\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const char * \fBgetName\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<Operator Op> static const char* \fBCatch::Internal::OperatorTraits\fP< Op >::getName ()\fC [inline]\fP, \fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
