.TH "Catch::NameAndDesc" 3 "Wed Jun 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::NameAndDesc
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <catch\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNameAndDesc\fP (const char *_name='', const char *_description='')"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "const char * \fBdescription\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Catch::NameAndDesc::NameAndDesc (const char * _name = \fC''\fP, const char * _description = \fC''\fP)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "const char* Catch::NameAndDesc::description"

.SS "const char* Catch::NameAndDesc::name"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
