.TH "Catch::NonCopyable" 3 "Wed Jun 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::NonCopyable
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <catch\&.hpp>\fP
.PP
Inherited by \fBCatch::IShared\fP, and \fBCatch::Section\fP\fC [private]\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBNonCopyable\fP ()"
.br
.ti -1c
.RI "virtual \fB~NonCopyable\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Catch::NonCopyable::NonCopyable ()\fC [inline]\fP, \fC [protected]\fP"

.SS "virtual Catch::NonCopyable::~NonCopyable ()\fC [protected]\fP, \fC [virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
