.TH "Catch::Generators" 3 "Wed Jun 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::Generators
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T > \fBCompositeGenerator\fP< T > \fBbetween\fP (T from, T to)"
.br
.ti -1c
.RI "template<typename T > \fBCompositeGenerator\fP< T > \fBvalues\fP (T val1, T val2)"
.br
.ti -1c
.RI "template<typename T > \fBCompositeGenerator\fP< T > \fBvalues\fP (T val1, T val2, T val3)"
.br
.ti -1c
.RI "template<typename T > \fBCompositeGenerator\fP< T > \fBvalues\fP (T val1, T val2, T val3, T val4)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<typename T > \fBCompositeGenerator\fP<T> Catch::Generators::between (T from, T to)"

.SS "template<typename T > \fBCompositeGenerator\fP<T> Catch::Generators::values (T val1, T val2)"

.SS "template<typename T > \fBCompositeGenerator\fP<T> Catch::Generators::values (T val1, T val2, T val3)"

.SS "template<typename T > \fBCompositeGenerator\fP<T> Catch::Generators::values (T val1, T val2, T val3, T val4)"

.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
