.TH "Catch::Matchers::StdString::CasedString" 3 "Wed Jun 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::Matchers::StdString::CasedString
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <catch\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCasedString\fP (\fBstd::string\fP const &str, \fBCaseSensitive::Choice\fP caseSensitivity)"
.br
.ti -1c
.RI "\fBstd::string\fP \fBadjustString\fP (\fBstd::string\fP const &str) const"
.br
.ti -1c
.RI "\fBstd::string\fP \fBcaseSensitivitySuffix\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCaseSensitive::Choice\fP \fBm_caseSensitivity\fP"
.br
.ti -1c
.RI "\fBstd::string\fP \fBm_str\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Catch::Matchers::StdString::CasedString::CasedString (\fBstd::string\fP const & str, \fBCaseSensitive::Choice\fP caseSensitivity)"

.SH "Member Function Documentation"
.PP 
.SS "\fBstd::string\fP Catch::Matchers::StdString::CasedString::adjustString (\fBstd::string\fP const & str) const"

.SS "\fBstd::string\fP Catch::Matchers::StdString::CasedString::caseSensitivitySuffix () const"

.SH "Member Data Documentation"
.PP 
.SS "\fBCaseSensitive::Choice\fP Catch::Matchers::StdString::CasedString::m_caseSensitivity"

.SS "\fBstd::string\fP Catch::Matchers::StdString::CasedString::m_str"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
