.TH "Catch::Timer" 3 "Wed Jun 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::Timer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <catch\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTimer\fP ()"
.br
.ti -1c
.RI "void \fBstart\fP ()"
.br
.ti -1c
.RI "unsigned int \fBgetElapsedMicroseconds\fP () const"
.br
.ti -1c
.RI "unsigned int \fBgetElapsedMilliseconds\fP () const"
.br
.ti -1c
.RI "double \fBgetElapsedSeconds\fP () const"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Catch::Timer::Timer ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "unsigned int Catch::Timer::getElapsedMicroseconds () const"

.SS "unsigned int Catch::Timer::getElapsedMilliseconds () const"

.SS "double Catch::Timer::getElapsedSeconds () const"

.SS "void Catch::Timer::start ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
