.TH "Catch::TestCaseInfo" 3 "Wed Jun 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::TestCaseInfo
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <catch\&.hpp>\fP
.PP
Inherited by \fBCatch::TestCase\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBSpecialProperties\fP { \fBNone\fP = 0, \fBIsHidden\fP = 1 << 1, \fBShouldFail\fP = 1 << 2, \fBMayFail\fP = 1 << 3, \fBThrows\fP = 1 << 4, \fBNonPortable\fP = 1 << 5 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTestCaseInfo\fP (\fBstd::string\fP const &_name, \fBstd::string\fP const &_className, \fBstd::string\fP const &_description, \fBstd::set\fP< \fBstd::string\fP > const &_tags, \fBSourceLineInfo\fP const &_lineInfo)"
.br
.ti -1c
.RI "\fBTestCaseInfo\fP (\fBTestCaseInfo\fP const &other)"
.br
.ti -1c
.RI "bool \fBisHidden\fP () const"
.br
.ti -1c
.RI "bool \fBthrows\fP () const"
.br
.ti -1c
.RI "bool \fBokToFail\fP () const"
.br
.ti -1c
.RI "bool \fBexpectedToFail\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstd::string\fP \fBname\fP"
.br
.ti -1c
.RI "\fBstd::string\fP \fBclassName\fP"
.br
.ti -1c
.RI "\fBstd::string\fP \fBdescription\fP"
.br
.ti -1c
.RI "\fBstd::set\fP< \fBstd::string\fP > \fBtags\fP"
.br
.ti -1c
.RI "\fBstd::set\fP< \fBstd::string\fP > \fBlcaseTags\fP"
.br
.ti -1c
.RI "\fBstd::string\fP \fBtagsAsString\fP"
.br
.ti -1c
.RI "\fBSourceLineInfo\fP \fBlineInfo\fP"
.br
.ti -1c
.RI "\fBSpecialProperties\fP \fBproperties\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "void \fBsetTags\fP (\fBTestCaseInfo\fP &testCaseInfo, \fBstd::set\fP< \fBstd::string\fP > const &\fBtags\fP)"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBCatch::TestCaseInfo::SpecialProperties\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINone \fP\fP
.TP
\fB\fIIsHidden \fP\fP
.TP
\fB\fIShouldFail \fP\fP
.TP
\fB\fIMayFail \fP\fP
.TP
\fB\fIThrows \fP\fP
.TP
\fB\fINonPortable \fP\fP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Catch::TestCaseInfo::TestCaseInfo (\fBstd::string\fP const & _name, \fBstd::string\fP const & _className, \fBstd::string\fP const & _description, \fBstd::set\fP< \fBstd::string\fP > const & _tags, \fBSourceLineInfo\fP const & _lineInfo)"

.SS "Catch::TestCaseInfo::TestCaseInfo (\fBTestCaseInfo\fP const & other)"

.SH "Member Function Documentation"
.PP 
.SS "bool Catch::TestCaseInfo::expectedToFail () const"

.SS "bool Catch::TestCaseInfo::isHidden () const"

.SS "bool Catch::TestCaseInfo::okToFail () const"

.SS "bool Catch::TestCaseInfo::throws () const"

.SH "Friends And Related Function Documentation"
.PP 
.SS "void setTags (\fBTestCaseInfo\fP & testCaseInfo, \fBstd::set\fP< \fBstd::string\fP > const & tags)\fC [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBstd::string\fP Catch::TestCaseInfo::className"

.SS "\fBstd::string\fP Catch::TestCaseInfo::description"

.SS "\fBstd::set\fP<\fBstd::string\fP> Catch::TestCaseInfo::lcaseTags"

.SS "\fBSourceLineInfo\fP Catch::TestCaseInfo::lineInfo"

.SS "\fBstd::string\fP Catch::TestCaseInfo::name"

.SS "\fBSpecialProperties\fP Catch::TestCaseInfo::properties"

.SS "\fBstd::set\fP<\fBstd::string\fP> Catch::TestCaseInfo::tags"

.SS "\fBstd::string\fP Catch::TestCaseInfo::tagsAsString"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
