.TH "Catch::Matchers::Impl::MatcherMethod< PtrT * >" 3 "Wed Jun 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::Matchers::Impl::MatcherMethod< PtrT * >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <catch\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBmatch\fP (PtrT *arg) const =0"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<typename PtrT > virtual bool \fBCatch::Matchers::Impl::MatcherMethod\fP< PtrT * >::match (PtrT * arg) const\fC [pure virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
