.TH "Catch::Detail::BorgType" 3 "Wed Jun 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::Detail::BorgType
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <catch\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename T > \fBBorgType\fP (T const &)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T > Catch::Detail::BorgType::BorgType (T const &)"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
