.TH "Catch::AssertionInfo" 3 "Wed Jun 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::AssertionInfo
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <catch\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAssertionInfo\fP ()"
.br
.ti -1c
.RI "\fBAssertionInfo\fP (\fBstd::string\fP const &_macroName, \fBSourceLineInfo\fP const &_lineInfo, \fBstd::string\fP const &_capturedExpression, \fBResultDisposition::Flags\fP _resultDisposition)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstd::string\fP \fBmacroName\fP"
.br
.ti -1c
.RI "\fBSourceLineInfo\fP \fBlineInfo\fP"
.br
.ti -1c
.RI "\fBstd::string\fP \fBcapturedExpression\fP"
.br
.ti -1c
.RI "\fBResultDisposition::Flags\fP \fBresultDisposition\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Catch::AssertionInfo::AssertionInfo ()\fC [inline]\fP"

.SS "Catch::AssertionInfo::AssertionInfo (\fBstd::string\fP const & _macroName, \fBSourceLineInfo\fP const & _lineInfo, \fBstd::string\fP const & _capturedExpression, \fBResultDisposition::Flags\fP _resultDisposition)"

.SH "Member Data Documentation"
.PP 
.SS "\fBstd::string\fP Catch::AssertionInfo::capturedExpression"

.SS "\fBSourceLineInfo\fP Catch::AssertionInfo::lineInfo"

.SS "\fBstd::string\fP Catch::AssertionInfo::macroName"

.SS "\fBResultDisposition::Flags\fP Catch::AssertionInfo::resultDisposition"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
