.TH "Catch::Totals" 3 "Wed Jun 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::Totals
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <catch\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTotals\fP \fBoperator\-\fP (\fBTotals\fP const &other) const"
.br
.ti -1c
.RI "\fBTotals\fP \fBdelta\fP (\fBTotals\fP const &prevTotals) const"
.br
.ti -1c
.RI "\fBTotals\fP & \fBoperator+=\fP (\fBTotals\fP const &other)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCounts\fP \fBassertions\fP"
.br
.ti -1c
.RI "\fBCounts\fP \fBtestCases\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBTotals\fP Catch::Totals::delta (\fBTotals\fP const & prevTotals) const\fC [inline]\fP"

.SS "\fBTotals\fP& Catch::Totals::operator+= (\fBTotals\fP const & other)\fC [inline]\fP"

.SS "\fBTotals\fP Catch::Totals::operator\- (\fBTotals\fP const & other) const\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBCounts\fP Catch::Totals::assertions"

.SS "\fBCounts\fP Catch::Totals::testCases"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
