.TH "Catch::TagAlias" 3 "Wed Jun 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::TagAlias
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <catch\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTagAlias\fP (\fBstd::string\fP const &_tag, \fBSourceLineInfo\fP _lineInfo)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstd::string\fP \fBtag\fP"
.br
.ti -1c
.RI "\fBSourceLineInfo\fP \fBlineInfo\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Catch::TagAlias::TagAlias (\fBstd::string\fP const & _tag, \fBSourceLineInfo\fP _lineInfo)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBSourceLineInfo\fP Catch::TagAlias::lineInfo"

.SS "\fBstd::string\fP Catch::TagAlias::tag"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
