.TH "Catch::IExceptionTranslator" 3 "Wed Jun 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::IExceptionTranslator
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <catch\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~IExceptionTranslator\fP ()"
.br
.ti -1c
.RI "virtual \fBstd::string\fP \fBtranslate\fP (ExceptionTranslators::const_iterator it, ExceptionTranslators::const_iterator itEnd) const =0"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual Catch::IExceptionTranslator::~IExceptionTranslator ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual \fBstd::string\fP Catch::IExceptionTranslator::translate (ExceptionTranslators::const_iterator it, ExceptionTranslators::const_iterator itEnd) const\fC [pure virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
