.TH "Catch::Internal::Evaluator< T1, T2, IsGreaterThanOrEqualTo >" 3 "Wed Jun 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::Internal::Evaluator< T1, T2, IsGreaterThanOrEqualTo >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <catch\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBevaluate\fP (T1 const &lhs, T2 const &rhs)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<typename T1 , typename T2 > static bool \fBCatch::Internal::Evaluator\fP< T1, T2, \fBIsGreaterThanOrEqualTo\fP >::evaluate (T1 const & lhs, T2 const & rhs)\fC [inline]\fP, \fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
