.TH "Catch::Detail::StringMakerBase< C >" 3 "Wed Jun 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::Detail::StringMakerBase< C >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <catch\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename T > static \fBstd::string\fP \fBconvert\fP (T const &)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<bool C> template<typename T > static \fBstd::string\fP \fBCatch::Detail::StringMakerBase\fP< C >::convert (T const &)\fC [inline]\fP, \fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
