.TH "Catch::ScopedMessage" 3 "Wed Jun 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::ScopedMessage
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <catch\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScopedMessage\fP (\fBMessageBuilder\fP const &builder)"
.br
.ti -1c
.RI "\fBScopedMessage\fP (\fBScopedMessage\fP const &other)"
.br
.ti -1c
.RI "\fB~ScopedMessage\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMessageInfo\fP \fBm_info\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Catch::ScopedMessage::ScopedMessage (\fBMessageBuilder\fP const & builder)"

.SS "Catch::ScopedMessage::ScopedMessage (\fBScopedMessage\fP const & other)"

.SS "Catch::ScopedMessage::~ScopedMessage ()"

.SH "Member Data Documentation"
.PP 
.SS "\fBMessageInfo\fP Catch::ScopedMessage::m_info"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
