.TH "Catch::Internal::Evaluator< T1, T2, Op >" 3 "Wed Jun 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::Internal::Evaluator< T1, T2, Op >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <catch\&.hpp>\fP

.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
