.TH "Catch::IExceptionTranslatorRegistry" 3 "Wed Jun 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::IExceptionTranslatorRegistry
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <catch\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~IExceptionTranslatorRegistry\fP ()"
.br
.ti -1c
.RI "virtual \fBstd::string\fP \fBtranslateActiveException\fP () const =0"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual Catch::IExceptionTranslatorRegistry::~IExceptionTranslatorRegistry ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual \fBstd::string\fP Catch::IExceptionTranslatorRegistry::translateActiveException () const\fC [pure virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
