.TH "Catch::StringMaker< R C::* >" 3 "Wed Jun 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::StringMaker< R C::* >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <catch\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBstd::string\fP \fBconvert\fP (R C::*p)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<typename R , typename C > static \fBstd::string\fP \fBCatch::StringMaker\fP< R C::* >::convert (R C::* p)\fC [inline]\fP, \fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
