.TH "Catch::ExceptionTranslatorRegistrar" 3 "Wed Jun 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::ExceptionTranslatorRegistrar
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <catch\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename T > \fBExceptionTranslatorRegistrar\fP (\fBstd::string\fP(*translateFunction)(T &))"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T > Catch::ExceptionTranslatorRegistrar::ExceptionTranslatorRegistrar (\fBstd::string\fP(*)(T &) translateFunction)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
