.TH "Catch::pluralise" 3 "Wed Jun 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::pluralise
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <catch\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBpluralise\fP (\fBstd::size_t\fP count, \fBstd::string\fP const &label)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstd::size_t\fP \fBm_count\fP"
.br
.ti -1c
.RI "\fBstd::string\fP \fBm_label\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBstd::ostream\fP & \fBoperator<<\fP (\fBstd::ostream\fP &os, \fBpluralise\fP const &pluraliser)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Catch::pluralise::pluralise (\fBstd::size_t\fP count, \fBstd::string\fP const & label)"

.SH "Friends And Related Function Documentation"
.PP 
.SS "\fBstd::ostream\fP& operator<< (\fBstd::ostream\fP & os, \fBpluralise\fP const & pluraliser)\fC [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBstd::size_t\fP Catch::pluralise::m_count"

.SS "\fBstd::string\fP Catch::pluralise::m_label"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
