.TH "Catch::ITestCase" 3 "Wed Jun 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::ITestCase
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <catch\&.hpp>\fP
.PP
Inherits \fBCatch::IShared\fP\&.
.PP
Inherited by \fBCatch::SharedImpl< ITestCase >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBinvoke\fP () const =0"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~ITestCase\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual Catch::ITestCase::~ITestCase ()\fC [protected]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual void Catch::ITestCase::invoke () const\fC [pure virtual]\fP"

.PP
Implemented in \fBCatch::MethodTestCase< C >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
