.TH "ConditionalExpression" 3 "Sat Apr 29 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConditionalExpression
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBExpression\fP \fBtest\fP"
.br
.ti -1c
.RI "\fBExpression\fP \fBconsequent\fP"
.br
.ti -1c
.RI "\fBExpression\fP \fBalternate\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBExpression\fP ConditionalExpression::alternate"

.SS "\fBExpression\fP ConditionalExpression::consequent"

.SS "\fBExpression\fP ConditionalExpression::test"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
