.TH "ContinueStatement" 3 "Sat Jun 10 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContinueStatement
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.PP
Inherits \fBStatement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBContinueStatement\fP (\fBIdentifier\fP *\fBlabel\fP=nullptr)"
.br
.ti -1c
.RI "void \fBaccept\fP (\fBVisitor\fP &visitor) const override"
.br
.ti -1c
.RI "const char * \fBtype\fP () const override"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBIdentifier\fP * \fBlabel\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ContinueStatement::ContinueStatement (\fBIdentifier\fP * label = \fCnullptr\fP)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void ContinueStatement::accept (\fBVisitor\fP & visitor) const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBNode\fP\&.
.SS "const char* ContinueStatement::type () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBNode\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBIdentifier\fP* ContinueStatement::label"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
