.TH "src/crc32.h" 3 "Sun May 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/crc32.h
.SH SYNOPSIS
.br
.PP
\fC#include <cstdint>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "constexpr uint32_t \fBcrc32\fP (const char *p)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static constexpr uint32_t \fBcrc32_tab\fP []"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "constexpr uint32_t crc32 (const char * p)"

.SH "Variable Documentation"
.PP 
.SS "constexpr uint32_t crc32_tab[]\fC [static]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
