.TH "src/declarative_environment_record.h" 3 "Sat Jun 10 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/declarative_environment_record.h
.SH SYNOPSIS
.br
.PP
\fC#include 'environment_record\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBDeclarativeEnvironmentRecord\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
