.TH "DefaultClause" 3 "Tue May 2 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DefaultClause
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.PP
Inherits \fBCaseClause\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDefaultClause\fP (\fBStatementList\fP *\fBconsequent\fP)"
.br
.ti -1c
.RI "void \fBaccept\fP (\fBVisitor\fP &visitor) const override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DefaultClause::DefaultClause (\fBStatementList\fP * consequent)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void DefaultClause::accept (\fBVisitor\fP & visitor) const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBCaseClause\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
