.TH "detail::is_callable1< T, F, void_t< decltype(std::declval< F >()(std::declval< T >()))> >" 3 "Tue May 2 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
detail::is_callable1< T, F, void_t< decltype(std::declval< F >()(std::declval< T >()))> >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBstd::true_type\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
