.TH "detail" 3 "Tue May 2 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
detail
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBis_callable1\fP"
.br
.ti -1c
.RI "struct \fBis_callable1< T, F, void_t< decltype(std::declval< F >()(std::declval< T >()))> >\fP"
.br
.ti -1c
.RI "struct \fBis_callable2\fP"
.br
.ti -1c
.RI "struct \fBis_callable2< T, N, F, void_t< decltype(std::declval< F >()(std::declval< T >(), std::declval< N >()))> >\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , typename N , typename F > auto \fBapply\fP (T &&value, N &&next, F &&callback)"
.br
.ti -1c
.RI "template<typename T , typename N , typename F > void \fBapply\fP (T &&value, N &&next, F &&callback, \fBstd::true_type\fP, \fBstd::false_type\fP)"
.br
.ti -1c
.RI "template<typename T , typename N , typename F > void \fBapply\fP (T &&value, N &&, F &&callback, \fBstd::false_type\fP, \fBstd::true_type\fP)"
.br
.ti -1c
.RI "template<typename T , typename N , typename F > void \fBapply\fP (T &&value, N &&, F &&callback, \fBstd::false_type\fP, \fBstd::false_type\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<typename T , typename N , typename F > auto detail::apply (T && value, N && next, F && callback)"

.SS "template<typename T , typename N , typename F > void detail::apply (T && value, N && next, F && callback, \fBstd::true_type\fP, \fBstd::false_type\fP)"

.SS "template<typename T , typename N , typename F > void detail::apply (T && value, N &&, F && callback, \fBstd::false_type\fP, \fBstd::true_type\fP)"

.SS "template<typename T , typename N , typename F > void detail::apply (T && value, N &&, F && callback, \fBstd::false_type\fP, \fBstd::false_type\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
