.TH "detail::is_callable2< class, class, class, class >" 3 "Tue May 2 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
detail::is_callable2< class, class, class, class >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBstd::false_type\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
