.TH "src/execution_context.h" 3 "Sat Jun 10 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/execution_context.h
.SH SYNOPSIS
.br
.PP
\fC#include 'environment_record\&.h'\fP
.br
\fC#include <memory>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBLexicalEnvironment\fP"
.br
.ti -1c
.RI "struct \fBExecutionContext\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
