.TH "ExecutionContext" 3 "Wed Jun 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExecutionContext
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <eval_visitor\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLexicalEnvironment\fP * \fBLexicalEnvironemnt\fP"
.br
.ti -1c
.RI "\fBLexicalEnvironment\fP * \fBVariableEnvironment\fP"
.br
.ti -1c
.RI "\fBType\fP \fBThisBinding\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBLexicalEnvironment\fP* ExecutionContext::LexicalEnvironemnt"

.SS "\fBType\fP ExecutionContext::ThisBinding"

.SS "\fBLexicalEnvironment\fP* ExecutionContext::VariableEnvironment"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
