.TH "Expression" 3 "Sun May 7 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Expression
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.PP
Inherits \fBNode\fP\&.
.PP
Inherited by \fBArguments\fP, \fBBinaryExpression\fP, \fBCallExpression\fP, \fBConditionalExpression\fP, \fBFunctionExpression\fP, \fBLeftHandSideExpression\fP, \fBMemberExpression\fP, \fBNewExpression\fP, \fBPostfixExpression\fP, \fBPropertyAssignment\fP, \fBPropertyName\fP, \fBUnaryExpression\fP, and \fBVariableDeclaration\fP\&.
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
