.TH "ExpressionBuilder" 3 "Sat Apr 29 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExpressionBuilder
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <parser\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBpush\fP (\fBExpression\fP &&value)"
.br
.ti -1c
.RI "template<typename T , typename\&.\&.\&. Args> void \fBpush\fP (Args &&\&.\&.\&. args)"
.br
.ti -1c
.RI "\fBExpression\fP \fBpop\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBExpression\fP ExpressionBuilder::pop ()\fC [inline]\fP"

.SS "void ExpressionBuilder::push (\fBExpression\fP && value)\fC [inline]\fP"

.SS "template<typename T , typename\&.\&.\&. Args> void ExpressionBuilder::push (Args &&\&.\&.\&. args)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
