.TH "ExpressionStatement" 3 "Sat Apr 29 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExpressionStatement
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBExpression\fP \fBexpression\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBExpression\fP ExpressionStatement::expression"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
