.TH "FunctionExpression" 3 "Sat Apr 29 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FunctionExpression
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "boost::optional< \fBIdentifier\fP > \fBid\fP"
.br
.ti -1c
.RI "\fBFormalParameterList\fP \fBparams\fP"
.br
.ti -1c
.RI "\fBFunctionBody\fP \fBbody\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBFunctionBody\fP FunctionExpression::body"

.SS "boost::optional<\fBIdentifier\fP> FunctionExpression::id"

.SS "\fBFormalParameterList\fP FunctionExpression::params"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
