.TH "IdentifierExpression" 3 "Sat Jun 10 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IdentifierExpression
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.PP
Inherits \fBPrimaryExpression\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIdentifierExpression\fP (\fBIdentifier\fP *\fBidentifier\fP)"
.br
.ti -1c
.RI "void \fBaccept\fP (\fBVisitor\fP &visitor) const override"
.br
.ti -1c
.RI "const char * \fBtype\fP () const override"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBIdentifier\fP * \fBidentifier\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IdentifierExpression::IdentifierExpression (\fBIdentifier\fP * identifier)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void IdentifierExpression::accept (\fBVisitor\fP & visitor) const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBNode\fP\&.
.SS "const char* IdentifierExpression::type () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBNode\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBIdentifier\fP* IdentifierExpression::identifier"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
