.TH "IfStatement" 3 "Wed Jun 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IfStatement
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.PP
Inherits \fBStatement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIfStatement\fP (\fBExpression\fP *\fBtest\fP, \fBStatement\fP *\fBconsequent\fP, \fBStatement\fP *\fBalternate\fP=nullptr)"
.br
.ti -1c
.RI "void \fBaccept\fP (\fBVisitor\fP &visitor) const override"
.br
.ti -1c
.RI "const char * \fBtype\fP () const override"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBExpression\fP * \fBtest\fP"
.br
.ti -1c
.RI "\fBStatement\fP * \fBconsequent\fP"
.br
.ti -1c
.RI "\fBStatement\fP * \fBalternate\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IfStatement::IfStatement (\fBExpression\fP * test, \fBStatement\fP * consequent, \fBStatement\fP * alternate = \fCnullptr\fP)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void IfStatement::accept (\fBVisitor\fP & visitor) const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBNode\fP\&.
.SS "const char* IfStatement::type () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBNode\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBStatement\fP* IfStatement::alternate"

.SS "\fBStatement\fP* IfStatement::consequent"

.SS "\fBExpression\fP* IfStatement::test"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
