.TH "indentstream" 3 "Tue May 2 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
indentstream
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBindent\fP ()"
.br
.ti -1c
.RI "void \fBunindent\fP ()"
.br
.ti -1c
.RI "template<typename T > \fBindentstream\fP \fBoperator<<\fP (T &&what)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstd::ostream\fP & \fBout\fP"
.br
.ti -1c
.RI "\fBstd::string\fP \fBm_incr\fP = ' '"
.br
.ti -1c
.RI "\fBstd::string\fP \fBm_indent\fP = ''"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void indentstream::indent ()\fC [inline]\fP"

.SS "template<typename T > \fBindentstream\fP indentstream::operator<< (T && what)\fC [inline]\fP"

.SS "void indentstream::unindent ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBstd::string\fP indentstream::m_incr = ' '"

.SS "\fBstd::string\fP indentstream::m_indent = ''"

.SS "\fBstd::ostream\fP& indentstream::out"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
