.TH "src/input_element.cpp" 3 "Sun May 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/input_element.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'input_element\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBis_line_terminator\fP (int cp)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool is_line_terminator (int cp)"

.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
