.TH "src/json.h" 3 "Sat Jun 10 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/json.h
.SH SYNOPSIS
.br
.PP
\fC#include 'types/string\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBString\fP \fBQuote\fP (const \fBString\fP &value)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBString\fP Quote (const \fBString\fP & value)"

.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
