.TH "JSONVisitor" 3 "Sat Jun 10 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JSONVisitor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json_visitor\&.h>\fP
.PP
Inherits \fBBasicVisitor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstd::string\fP \fBstr\fP () const"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBstd::string\fP JSONVisitor::str () const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
