.TH "src/json.cpp" 3 "Sat Jun 10 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/json.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'json\&.h'\fP
.br
\fC#include <stdexcept>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static constexpr char16_t \fBToHexDigit\fP (int x)"
.br
.ti -1c
.RI "\fBString\fP \fBQuote\fP (const \fBString\fP &value)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBString\fP Quote (const \fBString\fP & value)"

.SS "static constexpr char16_t ToHexDigit (int x)\fC [inline]\fP, \fC [static]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
