.TH "LexicalEnvironment" 3 "Sat Jun 10 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LexicalEnvironment
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <execution_context\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstd::unique_ptr\fP< \fBEnvironmentRecord\fP > \fBrecord\fP"
.br
.ti -1c
.RI "\fBLexicalEnvironment\fP * \fBouter\fP"
.br
.ti -1c
.RI "\fBstd::unique_ptr\fP< \fBEnvironmentRecord\fP > \fBenvRec\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBstd::unique_ptr\fP<\fBEnvironmentRecord\fP> LexicalEnvironment::envRec"

.SS "\fBLexicalEnvironment\fP * LexicalEnvironment::outer"

.SS "\fBstd::unique_ptr\fP<\fBEnvironmentRecord\fP> LexicalEnvironment::record"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
