.TH "List< T >" 3 "Sun May 7 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
List< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.PP
Inherits \fBNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename\&.\&.\&. Args> \fBList\fP (Args &&\&.\&.\&. args)"
.br
.ti -1c
.RI "\fBList\fP (T *arg)"
.br
.ti -1c
.RI "auto \fBfront\fP () const"
.br
.ti -1c
.RI "auto \fBback\fP () const"
.br
.ti -1c
.RI "void \fBpop_back\fP ()"
.br
.ti -1c
.RI "void \fBpush_back\fP (T *value)"
.br
.ti -1c
.RI "auto \fBbegin\fP () const"
.br
.ti -1c
.RI "auto \fBend\fP () const"
.br
.ti -1c
.RI "auto \fBoperator[]\fP (\fBstd::size_t\fP index)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstd::vector\fP< T * > \fBdata\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T> template<typename\&.\&.\&. Args> \fBList\fP< T >::\fBList\fP (Args &&\&.\&.\&. args)\fC [inline]\fP"

.SS "template<typename T> \fBList\fP< T >::\fBList\fP (T * arg)\fC [inline]\fP, \fC [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename T> auto \fBList\fP< T >::back () const\fC [inline]\fP"

.SS "template<typename T> auto \fBList\fP< T >::begin () const\fC [inline]\fP"

.SS "template<typename T> auto \fBList\fP< T >::end () const\fC [inline]\fP"

.SS "template<typename T> auto \fBList\fP< T >::front () const\fC [inline]\fP"

.SS "template<typename T> auto \fBList\fP< T >::operator[] (\fBstd::size_t\fP index)\fC [inline]\fP"

.SS "template<typename T> void \fBList\fP< T >::pop_back ()\fC [inline]\fP"

.SS "template<typename T> void \fBList\fP< T >::push_back (T * value)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<typename T> \fBstd::vector\fP<T*> \fBList\fP< T >::data"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
