.TH "Literal" 3 "Tue May 30 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Literal
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.PP
Inherits \fBNode\fP\&.
.PP
Inherited by \fBBooleanLiteral\fP, \fBNullLiteral\fP, \fBNumericLiteral\fP, \fBRegularExpressionLiteral\fP, and \fBStringLiteral\fP\&.
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
