.TH "src/logger.cpp" 3 "Sat Jun 10 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/logger.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'logger\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSilentLogger\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBLogger\fP * \fBmake_silent_logger\fP ()"
.br
.ti -1c
.RI "\fBLogger\fP & \fBoperator<<\fP (\fBLogger\fP &out, const \fBstd::string\fP &str)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBLogger\fP* make_silent_logger ()"

.SS "\fBLogger\fP& operator<< (\fBLogger\fP & out, const \fBstd::string\fP & str)"

.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
