.TH "src/main.cpp" 3 "Sat Jun 10 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'eval\&.h'\fP
.br
\fC#include 'lexer\&.h'\fP
.br
\fC#include 'parser\&.h'\fP
.br
\fC#include 'util\&.h'\fP
.br
\fC#include 'ast_visitor\&.h'\fP
.br
\fC#include 'eval_visitor\&.h'\fP
.br
\fC#include 'json_visitor\&.h'\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <iterator>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <boost/filesystem\&.hpp>\fP
.br
\fC#include <boost/program_options\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "template<class T > \fBstd::ostream\fP & \fBoperator<<\fP (\fBstd::ostream\fP &os, const \fBstd::vector\fP< T > &v)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, const char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, const char ** argv)"

.SS "template<class T > \fBstd::ostream\fP& operator<< (\fBstd::ostream\fP & os, const \fBstd::vector\fP< T > & v)"

.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
