.TH "MemberExpression" 3 "Sat Apr 29 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MemberExpression
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBExpression\fP \fBobject\fP"
.br
.ti -1c
.RI "\fBExpression\fP \fBproperty\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBExpression\fP MemberExpression::object"

.SS "\fBExpression\fP MemberExpression::property"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
