.TH "NewExpression" 3 "Sat Apr 29 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NewExpression
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBExpression\fP \fBcallee\fP"
.br
.ti -1c
.RI "\fBArguments\fP \fBarguments\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBArguments\fP NewExpression::arguments"

.SS "\fBExpression\fP NewExpression::callee"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
