.TH "Number" 3 "Sun Apr 30 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Number
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <types\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBisNaN\fP () const"
.br
.ti -1c
.RI "bool \fBisZero\fP () const"
.br
.ti -1c
.RI "bool \fBisInfinity\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBvalue\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool Number::isInfinity () const\fC [inline]\fP"

.SS "bool Number::isNaN () const\fC [inline]\fP"

.SS "bool Number::isZero () const\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "double Number::value"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
