.TH "ObjectLiteral" 3 "Sat Apr 29 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectLiteral
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstd::vector\fP< \fBPropertyAssignment\fP > \fBdeclarations\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBstd::vector\fP<\fBPropertyAssignment\fP> ObjectLiteral::declarations"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
