.TH "Object" 3 "Sat Jun 10 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Object
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <value\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBValue\fP \fBDefaultValue\fP () const"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBValue\fP Object::DefaultValue () const"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
