.TH "overloaded_t< T >" 3 "Wed Jun 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
overloaded_t< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits T\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBoverloaded_t\fP (T value)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T > \fBoverloaded_t\fP< T >::\fBoverloaded_t\fP (T value)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
