.TH "overloaded_t< T, Ts... >" 3 "Wed Jun 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
overloaded_t< T, Ts... >
.SH SYNOPSIS
.br
.PP
.PP
Inherits T, and \fBoverloaded_t< Ts\&.\&.\&. >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBoverloaded_t\fP (T head, Ts\&.\&.\&. tail)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T , class\&.\&.\&. Ts> \fBoverloaded_t\fP< T, Ts\&.\&.\&. >::\fBoverloaded_t\fP (T head, Ts\&.\&.\&. tail)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
