.TH "Parser" 3 "Wed Jun 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Parser
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <parser\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename\&.\&.\&. Args> \fBParser\fP (Args &&\&.\&.\&. args)"
.br
.ti -1c
.RI "\fBProgram\fP \fBparse\fP ()"
.br
.ti -1c
.RI "void \fBlogger\fP (\fBLogger\fP *logger=\fBmake_silent_logger\fP())"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename\&.\&.\&. Args> Parser::Parser (Args &&\&.\&.\&. args)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void Parser::logger (\fBLogger\fP * logger = \fC\fBmake_silent_logger\fP()\fP)\fC [inline]\fP"

.SS "\fBProgram\fP Parser::parse ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
