.TH "src/parser.cpp" 3 "Sun Apr 30 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/parser.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'parser\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBis_assignment_operator\fP (const \fBstd::string\fP &op)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool is_assignment_operator (const \fBstd::string\fP & op)"

.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
