.TH "src/parser.h" 3 "Wed Jun 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/parser.h
.SH SYNOPSIS
.br
.PP
\fC#include 'ast\&.h'\fP
.br
\fC#include 'logger\&.h'\fP
.br
\fC#include 'matcher\&.h'\fP
.br
\fC#include 'token\&.h'\fP
.br
\fC#include 'trace\&.h'\fP
.br
\fC#include 'util\&.h'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSyntaxError\fP"
.br
.ti -1c
.RI "class \fBParser\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename It > \fBParser\fP \fBmake_parser\fP (It f, It l)"
.br
.ti -1c
.RI "template<typename Cont > auto \fBmake_parser\fP (Cont &&cont)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<typename It > \fBParser\fP make_parser (It f, It l)"

.SS "template<typename Cont > auto make_parser (Cont && cont)"

.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
