.TH "src/pimpl.h" 3 "Sat Jun 10 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/pimpl.h
.SH SYNOPSIS
.br
.PP
\fC#include <memory>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "template<typename T > using \fBPimpl\fP = const \fBstd::unique_ptr\fP< T >"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "template<typename T > using \fBPimpl\fP =  const \fBstd::unique_ptr\fP<T>"

.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
