.TH "PrimaryExpression" 3 "Tue May 2 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PrimaryExpression
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.PP
Inherits \fBExpression\fP\&.
.PP
Inherited by \fBArrayLiteral\fP, \fBIdentifier\fP, \fBLiteral\fP, \fBObjectLiteral\fP, and \fBThis\fP\&.
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
