.TH "print" 3 "Sat Jun 10 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
print
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBoperator()\fP (const \fBUndefined\fP &) const"
.br
.ti -1c
.RI "void \fBoperator()\fP (const \fBNull\fP &) const"
.br
.ti -1c
.RI "void \fBoperator()\fP (const \fBBoolean\fP &) const"
.br
.ti -1c
.RI "void \fBoperator()\fP (const \fBString\fP &) const"
.br
.ti -1c
.RI "void \fBoperator()\fP (const \fBNumber\fP &) const"
.br
.ti -1c
.RI "void \fBoperator()\fP (\&.\&.\&.) const"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void print::operator() (const \fBUndefined\fP &) const\fC [inline]\fP"

.SS "void print::operator() (const \fBNull\fP &) const\fC [inline]\fP"

.SS "void print::operator() (const \fBBoolean\fP &) const\fC [inline]\fP"

.SS "void print::operator() (const \fBString\fP &) const\fC [inline]\fP"

.SS "void print::operator() (const \fBNumber\fP &) const\fC [inline]\fP"

.SS "void print::operator() ( \&.\&.\&.) const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
