.TH "ProgramDeclaration" 3 "Sun May 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProgramDeclaration
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.PP
Inherits \fBDeclaration\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProgramDeclaration\fP (\fBSourceElements\fP *\fBbody\fP=nullptr)"
.br
.ti -1c
.RI "void \fBaccept\fP (\fBVisitor\fP &visitor) const override"
.br
.ti -1c
.RI "const char * \fBtype\fP () const override"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstd::vector\fP< \fBStringLiteral\fP * > \fBdirectives\fP"
.br
.ti -1c
.RI "\fBSourceElements\fP * \fBbody\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ProgramDeclaration::ProgramDeclaration (\fBSourceElements\fP * body = \fCnullptr\fP)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void ProgramDeclaration::accept (\fBVisitor\fP & visitor) const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBNode\fP\&.
.SS "const char* ProgramDeclaration::type () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBNode\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSourceElements\fP* ProgramDeclaration::body"

.SS "\fBstd::vector\fP<\fBStringLiteral\fP*> ProgramDeclaration::directives"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
