.TH "Program" 3 "Wed Jun 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Program
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBaccept\fP (\fBVisitor\fP &visitor) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstd::shared_ptr\fP< void > \fBstorage\fP"
.br
.ti -1c
.RI "\fBProgramDeclaration\fP * \fBbody\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void Program::accept (\fBVisitor\fP & visitor) const\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBProgramDeclaration\fP* Program::body"

.SS "\fBstd::shared_ptr\fP<void> Program::storage"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
