.TH "PropertyAssignment" 3 "Tue May 30 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PropertyAssignment
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.PP
Inherits \fBExpression\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBKind\fP { \fBKind::INIT\fP, \fBKind::GET\fP, \fBKind::SET\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPropertyAssignment\fP (\fBPropertyName\fP *\fBname\fP, \fBExpression\fP *\fBexpression\fP)"
.br
.ti -1c
.RI "\fBPropertyAssignment\fP (\fBPropertyName\fP *\fBname\fP, \fBFunctionBody\fP *\fBbody\fP)"
.br
.ti -1c
.RI "\fBPropertyAssignment\fP (\fBPropertyName\fP *\fBname\fP, \fBIdentifier\fP *\fBparameter\fP, \fBFunctionBody\fP *\fBbody\fP)"
.br
.ti -1c
.RI "void \fBaccept\fP (\fBVisitor\fP &visitor) const override"
.br
.ti -1c
.RI "const char * \fBtype\fP () const override"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "enum \fBPropertyAssignment::Kind\fP \fBkind\fP"
.br
.ti -1c
.RI "\fBPropertyName\fP * \fBname\fP"
.br
.ti -1c
.RI "\fBExpression\fP * \fBexpression\fP = nullptr"
.br
.ti -1c
.RI "\fBFunctionBody\fP * \fBbody\fP = nullptr"
.br
.ti -1c
.RI "\fBIdentifier\fP * \fBparameter\fP = nullptr"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBPropertyAssignment::Kind\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIINIT \fP\fP
.TP
\fB\fIGET \fP\fP
.TP
\fB\fISET \fP\fP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PropertyAssignment::PropertyAssignment (\fBPropertyName\fP * name, \fBExpression\fP * expression)\fC [inline]\fP"

.SS "PropertyAssignment::PropertyAssignment (\fBPropertyName\fP * name, \fBFunctionBody\fP * body)\fC [inline]\fP"

.SS "PropertyAssignment::PropertyAssignment (\fBPropertyName\fP * name, \fBIdentifier\fP * parameter, \fBFunctionBody\fP * body)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void PropertyAssignment::accept (\fBVisitor\fP & visitor) const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBNode\fP\&.
.SS "const char* PropertyAssignment::type () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBNode\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBFunctionBody\fP* PropertyAssignment::body = nullptr"

.SS "\fBExpression\fP* PropertyAssignment::expression = nullptr"

.SS "enum \fBPropertyAssignment::Kind\fP  PropertyAssignment::kind"

.SS "\fBPropertyName\fP* PropertyAssignment::name"

.SS "\fBIdentifier\fP* PropertyAssignment::parameter = nullptr"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
