.TH "Reference" 3 "Wed Jun 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Reference
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <runtime\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBType\fP \fBbase\fP"
.br
.ti -1c
.RI "\fBString\fP \fBname\fP"
.br
.ti -1c
.RI "\fBBoolean\fP \fBstrict\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBType\fP Reference::base"

.SS "\fBString\fP Reference::name"

.SS "\fBBoolean\fP Reference::strict"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
