.TH "SilentLogger" 3 "Tue May 30 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SilentLogger
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLogger\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBlog\fP (const \fBstd::string\fP &what) final"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void SilentLogger::log (const \fBstd::string\fP & what)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Implements \fBLogger\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
