.TH "SourceElement" 3 "Tue May 2 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceElement
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.PP
Inherits \fBNode\fP\&.
.PP
Inherited by \fBDeclaration\fP, \fBFunctionDeclaration\fP, and \fBStatement\fP\&.
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
