.TH "SourceElements" 3 "Tue May 30 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceElements
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.PP
Inherits \fBList< SourceElement >\fP\&.
.PP
Inherited by \fBFunctionBody\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename\&.\&.\&. Args> \fBSourceElements\fP (Args &&\&.\&.\&. args)"
.br
.ti -1c
.RI "void \fBaccept\fP (\fBVisitor\fP &visitor) const override"
.br
.ti -1c
.RI "const char * \fBtype\fP () const override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename\&.\&.\&. Args> SourceElements::SourceElements (Args &&\&.\&.\&. args)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void SourceElements::accept (\fBVisitor\fP & visitor) const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBNode\fP\&.
.PP
Reimplemented in \fBFunctionBody\fP\&.
.SS "const char* SourceElements::type () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBNode\fP\&.
.PP
Reimplemented in \fBFunctionBody\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
