.TH "StandardLogger< T >" 3 "Wed Jun 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StandardLogger< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <logger\&.h>\fP
.PP
Inherits \fBLogger\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStandardLogger\fP (T &out)"
.br
.ti -1c
.RI "void \fBlog\fP (const \fBstd::string\fP &what) override"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T > \fBStandardLogger\fP< T >::\fBStandardLogger\fP (T & out)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename T > void \fBStandardLogger\fP< T >::log (const \fBstd::string\fP & what)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBLogger\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
