.TH "StatementBuilder" 3 "Sat Apr 29 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StatementBuilder
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <parser\&.h>\fP
.PP
Inherited by \fBStatementParser\fP\fC [private]\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBpush\fP (\fBStatement\fP &&stmt)"
.br
.ti -1c
.RI "template<typename T , typename\&.\&.\&. Args> void \fBpush\fP (Args &&\&.\&.\&. args)"
.br
.ti -1c
.RI "\fBStatement\fP \fBpop\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBStatement\fP StatementBuilder::pop ()\fC [inline]\fP"

.SS "void StatementBuilder::push (\fBStatement\fP && stmt)\fC [inline]\fP"

.SS "template<typename T , typename\&.\&.\&. Args> void StatementBuilder::push (Args &&\&.\&.\&. args)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
