.TH "StringConverter" 3 "Tue May 2 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StringConverter
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBasicLexer< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBstring_white_space\fP ()"
.br
.ti -1c
.RI "bool \fBstr_white_space\fP ()"
.br
.ti -1c
.RI "bool \fBstr_numeric_literal\fP ()"
.br
.ti -1c
.RI "bool \fBstr_decimal_literal\fP ()"
.br
.ti -1c
.RI "bool \fBstr_unsigned_decimal_literal\fP ()"
.br
.ti -1c
.RI "bool \fBdecimal_digits\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBsign\fP = +1"
.br
.ti -1c
.RI "double \fBvalue\fP"
.br
.ti -1c
.RI "int \fBdecimal_value\fP = 0"
.br
.ti -1c
.RI "int \fBdecimal_count\fP = 0"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool StringConverter::decimal_digits ()\fC [inline]\fP"

.SS "bool StringConverter::str_decimal_literal ()\fC [inline]\fP"

.SS "bool StringConverter::str_numeric_literal ()\fC [inline]\fP"

.SS "bool StringConverter::str_unsigned_decimal_literal ()\fC [inline]\fP"

.SS "bool StringConverter::str_white_space ()\fC [inline]\fP"

.SS "bool StringConverter::string_white_space ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "int StringConverter::decimal_count = 0"

.SS "int StringConverter::decimal_value = 0"

.SS "int StringConverter::sign = +1"

.SS "double StringConverter::value"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
