.TH "String" 3 "Sun May 7 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
String
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <types\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstd::u16string\fP \fBvalue\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBstd::u16string\fP String::value"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
