.TH "StringLiteral" 3 "Sat Apr 29 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StringLiteral
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstd::u16string\fP \fBvalue\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBstd::u16string\fP StringLiteral::value"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
