.TH "SwitchStatement" 3 "Tue May 2 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SwitchStatement
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.PP
Inherits \fBStatement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSwitchStatement\fP (\fBExpression\fP *\fBdiscriminant\fP, \fBCaseBlock\fP *\fBcases\fP)"
.br
.ti -1c
.RI "void \fBaccept\fP (\fBVisitor\fP &visitor) const override"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBExpression\fP * \fBdiscriminant\fP"
.br
.ti -1c
.RI "\fBCaseBlock\fP * \fBcases\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SwitchStatement::SwitchStatement (\fBExpression\fP * discriminant, \fBCaseBlock\fP * cases)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void SwitchStatement::accept (\fBVisitor\fP & visitor) const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBNode\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBCaseBlock\fP* SwitchStatement::cases"

.SS "\fBExpression\fP* SwitchStatement::discriminant"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
