.TH "src/syntax_error.h" 3 "Sat Jun 10 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/syntax_error.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdexcept>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSyntaxError\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
