.TH "src/test_value.cpp" 3 "Wed Jun 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test_value.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'util\&.h'\fP
.br
\fC#include 'value\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBprint\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
