.TH "ThrowStatement" 3 "Tue May 30 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ThrowStatement
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.PP
Inherits \fBStatement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBThrowStatement\fP (\fBExpression\fP *\fBargument\fP)"
.br
.ti -1c
.RI "void \fBaccept\fP (\fBVisitor\fP &visitor) const override"
.br
.ti -1c
.RI "const char * \fBtype\fP () const override"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBExpression\fP * \fBargument\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ThrowStatement::ThrowStatement (\fBExpression\fP * argument)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void ThrowStatement::accept (\fBVisitor\fP & visitor) const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBNode\fP\&.
.SS "const char* ThrowStatement::type () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBNode\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBExpression\fP* ThrowStatement::argument"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
