.TH "src/token.cpp" 3 "Tue May 30 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/token.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'token\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBstd::ostream\fP & \fBoperator<<\fP (\fBstd::ostream\fP &out, const \fBToken\fP &token)"
.br
.ti -1c
.RI "\fBstd::u16string\fP & \fBcreate_static_string\fP (\fBstd::u16string\fP value)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBstd::u16string\fP& create_static_string (\fBstd::u16string\fP value)"

.SS "\fBstd::ostream\fP& operator<< (\fBstd::ostream\fP & out, const \fBToken\fP & token)"

.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
