.TH "Token::DebugInfo" 3 "Sun May 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Token::DebugInfo
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <token\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBstd::string\fP \fBsyntax_error_at\fP () const =0"
.br
.ti -1c
.RI "virtual \fBstd::string\fP \fBloc\fP () const =0"
.br
.ti -1c
.RI "virtual \fBstd::string\fP \fBsyntax_error_at\fP () const =0"
.br
.ti -1c
.RI "virtual \fBstd::string\fP \fBloc\fP () const =0"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBstd::string\fP Token::DebugInfo::loc () const\fC [pure virtual]\fP"

.SS "virtual \fBstd::string\fP Token::DebugInfo::loc () const\fC [pure virtual]\fP"

.SS "virtual \fBstd::string\fP Token::DebugInfo::syntax_error_at () const\fC [pure virtual]\fP"

.SS "virtual \fBstd::string\fP Token::DebugInfo::syntax_error_at () const\fC [pure virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
