.TH "src/token.h" 3 "Wed Jun 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/token.h
.SH SYNOPSIS
.br
.PP
\fC#include 'util\&.h'\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <cstddef>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <string>\fP
.br
\fC#include <utility>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBToken\fP"
.br
.ti -1c
.RI "struct \fBToken::DebugInfo\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBstd::u16string\fP & \fBcreate_static_string\fP (\fBstd::u16string\fP value)"
.br
.ti -1c
.RI "\fBstd::ostream\fP & \fBoperator<<\fP (\fBstd::ostream\fP &out, const \fBToken\fP &token)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBstd::u16string\fP& create_static_string (\fBstd::u16string\fP value)"

.SS "\fBstd::ostream\fP& operator<< (\fBstd::ostream\fP & out, const \fBToken\fP & token)"

.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
