.TH "Token::print_visitor" 3 "Sun Apr 30 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Token::print_visitor
.SH SYNOPSIS
.br
.PP
.PP
Inherits static_visitor< void >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBprint_visitor\fP (\fBstd::ostream\fP &\fBout\fP)"
.br
.ti -1c
.RI "void \fBoperator()\fP (const Empty &) const"
.br
.ti -1c
.RI "void \fBoperator()\fP (const Identifier &\fBidentifier\fP) const"
.br
.ti -1c
.RI "void \fBoperator()\fP (const Keyword &\fBkeyword\fP) const"
.br
.ti -1c
.RI "void \fBoperator()\fP (const Punctuator &\fBpunctuator\fP) const"
.br
.ti -1c
.RI "void \fBoperator()\fP (const NullLiteral &) const"
.br
.ti -1c
.RI "void \fBoperator()\fP (const BooleanLiteral &literal) const"
.br
.ti -1c
.RI "void \fBoperator()\fP (const NumericLiteral &literal) const"
.br
.ti -1c
.RI "void \fBoperator()\fP (const StringLiteral &literal) const"
.br
.ti -1c
.RI "void \fBoperator()\fP (const RegularExpressionLiteral &literal) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstd::ostream\fP & \fBout\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Token::print_visitor::print_visitor (\fBstd::ostream\fP & out)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void Token::print_visitor::operator() (const Empty &) const\fC [inline]\fP"

.SS "void Token::print_visitor::operator() (const Identifier & identifier) const\fC [inline]\fP"

.SS "void Token::print_visitor::operator() (const Keyword & keyword) const\fC [inline]\fP"

.SS "void Token::print_visitor::operator() (const Punctuator & punctuator) const\fC [inline]\fP"

.SS "void Token::print_visitor::operator() (const NullLiteral &) const\fC [inline]\fP"

.SS "void Token::print_visitor::operator() (const BooleanLiteral & literal) const\fC [inline]\fP"

.SS "void Token::print_visitor::operator() (const NumericLiteral & literal) const\fC [inline]\fP"

.SS "void Token::print_visitor::operator() (const StringLiteral & literal) const\fC [inline]\fP"

.SS "void Token::print_visitor::operator() (const RegularExpressionLiteral & literal) const\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBstd::ostream\fP& Token::print_visitor::out"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
