.TH "Tracer" 3 "Sun May 7 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tracer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tracer\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBenter\fP (const char *, const char *, int)"
.br
.ti -1c
.RI "void \fBleave\fP ()"
.br
.ti -1c
.RI "const \fBstd::vector\fP< Line > & \fBstack\fP () const"
.br
.ti -1c
.RI "auto \fBbegin\fP () const"
.br
.ti -1c
.RI "auto \fBend\fP () const"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "auto Tracer::begin () const\fC [inline]\fP"

.SS "auto Tracer::end () const\fC [inline]\fP"

.SS "void Tracer::enter (const char * method, const char * file, int line)"

.SS "void Tracer::leave ()"

.SS "const \fBstd::vector\fP< Tracer::Line > & Tracer::stack () const"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
