.TH "src/tracer.h" 3 "Sun May 7 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/tracer.h
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTracer\fP"
.br
.ti -1c
.RI "class \fBTraceGuard\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTracer\fP & \fBtracer\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBTracer\fP& tracer ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
