.TH "src/trace.h" 3 "Wed Jun 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/trace.h
.SH SYNOPSIS
.br
.PP
\fC#include 'config\&.h'\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBTraceGuard\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBtrace\fP(\&.\&.\&.)   \fBTraceGuard\fP tg_##__LINE__(__PRETTY_FUNCTION__, __FILE__, __LINE__)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBstd::vector\fP< \fBstd::string\fP > & \fBstack_trace\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define trace( \&.\&.\&.)   \fBTraceGuard\fP tg_##__LINE__(__PRETTY_FUNCTION__, __FILE__, __LINE__)"

.SH "Function Documentation"
.PP 
.SS "\fBstd::vector\fP<\fBstd::string\fP>& stack_trace ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
