.TH "TraceGuard" 3 "Sat Jun 10 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TraceGuard
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <trace\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTraceGuard\fP (\fBstd::string\fP, \fBstd::string\fP='unnamed', int=1)"
.br
.ti -1c
.RI "\fB~TraceGuard\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TraceGuard::TraceGuard (\fBstd::string\fP method, \fBstd::string\fP file = \fC'unnamed'\fP, int line = \fC1\fP)"

.SS "TraceGuard::~TraceGuard ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
