.TH "Trace" 3 "Tue May 30 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Trace
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <trace\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBenter\fP (\fBstd::string\fP, \fBstd::string\fP, int)"
.br
.ti -1c
.RI "void \fBleave\fP ()"
.br
.ti -1c
.RI "const \fBstd::vector\fP< Line > & \fBstack\fP () const"
.br
.ti -1c
.RI "auto \fBbegin\fP () const"
.br
.ti -1c
.RI "auto \fBend\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBTrace\fP & \fBinstance\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "auto Trace::begin () const\fC [inline]\fP"

.SS "auto Trace::end () const\fC [inline]\fP"

.SS "void Trace::enter (\fBstd::string\fP method, \fBstd::string\fP file, int line)"

.SS "\fBTrace\fP & Trace::instance ()\fC [static]\fP"

.SS "void Trace::leave ()"

.SS "const \fBstd::vector\fP< Trace::Line > & Trace::stack () const"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
