.TH "src/types.h" 3 "Sun Apr 30 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/types.h
.SH SYNOPSIS
.br
.PP
\fC#include <cmath>\fP
.br
\fC#include <string>\fP
.br
\fC#include <boost/optional\&.hpp>\fP
.br
\fC#include <boost/variant\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBUndefined\fP"
.br
.ti -1c
.RI "struct \fBNull\fP"
.br
.ti -1c
.RI "struct \fBBoolean\fP"
.br
.ti -1c
.RI "struct \fBString\fP"
.br
.ti -1c
.RI "struct \fBNumber\fP"
.br
.ti -1c
.RI "struct \fBNamedDataProperty\fP"
.br
.ti -1c
.RI "struct \fBNamedAccessorProperty\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBType\fP = boost::variant< \fBUndefined\fP, \fBNull\fP, \fBBoolean\fP, \fBString\fP, \fBNumber\fP, boost::recursive_wrapper< \fBObject\fP > >"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBType\fP \fBGetBase\fP (\fBType\fP key)"
.br
.ti -1c
.RI "\fBType\fP \fBPutValue\fP (\fBType\fP key, \fBType\fP value)"
.br
.ti -1c
.RI "\fBType\fP \fBGetReferencedName\fP () \fBType\fP \fBToPrimitive\fP(\fBType\fP input"
.br
.ti -1c
.RI "\fBBoolean\fP \fBToBoolean\fP (\fBType\fP input)"
.br
.ti -1c
.RI "\fBNumber\fP \fBToNumber\fP (\fBType\fP input)"
.br
.ti -1c
.RI "\fBNumber\fP \fBToInteger\fP (\fBType\fP input)"
.br
.ti -1c
.RI "\fBNumber\fP \fBToInt32\fP (\fBType\fP input)"
.br
.ti -1c
.RI "\fBNumber\fP \fBToUint32\fP (\fBType\fP input)"
.br
.ti -1c
.RI "\fBNumber\fP \fBToUint16\fP (\fBType\fP input)"
.br
.ti -1c
.RI "\fBString\fP \fBToString\fP (\fBType\fP input)"
.br
.ti -1c
.RI "\fBObject\fP \fBToObject\fP (\fBType\fP input)"
.br
.ti -1c
.RI "\fBType\fP \fBCheckObjectCoercible\fP (\fBType\fP input)"
.br
.ti -1c
.RI "\fBBoolean\fP \fBIsCallable\fP (\fBType\fP input)"
.br
.ti -1c
.RI "\fBBoolean\fP \fBSameValue\fP (\fBType\fP input)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBNamedAccessorProperty\fP \fBObject\fP"
.br
.ti -1c
.RI "\fBType\fP boost::optional< \fBType\fP > \fBpreferred_type\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBType\fP =  boost::variant<\fBUndefined\fP, \fBNull\fP, \fBBoolean\fP, \fBString\fP, \fBNumber\fP, boost::recursive_wrapper<\fBObject\fP> >"

.SH "Function Documentation"
.PP 
.SS "\fBType\fP CheckObjectCoercible (\fBType\fP input)"

.SS "\fBType\fP GetBase (\fBType\fP key)"

.SS "\fBType\fP GetReferencedName ()"

.SS "\fBBoolean\fP IsCallable (\fBType\fP input)"

.SS "\fBType\fP PutValue (\fBType\fP key, \fBType\fP value)"

.SS "\fBBoolean\fP SameValue (\fBType\fP input)"

.SS "\fBBoolean\fP ToBoolean (\fBType\fP input)"

.SS "\fBNumber\fP ToInt32 (\fBType\fP input)"

.SS "\fBNumber\fP ToInteger (\fBType\fP input)"

.SS "\fBNumber\fP ToNumber (\fBType\fP input)"

.SS "\fBObject\fP ToObject (\fBType\fP input)"

.SS "\fBString\fP ToString (\fBType\fP input)"

.SS "\fBNumber\fP ToUint16 (\fBType\fP input)"

.SS "\fBNumber\fP ToUint32 (\fBType\fP input)"

.SH "Variable Documentation"
.PP 
.SS "struct \fBNamedAccessorProperty\fP Object"

.SS "\fBType\fP boost::optional<\fBType\fP> preferred_type"

.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
