.TH "UnaryExpression" 3 "Sun May 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnaryExpression
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.PP
Inherits \fBExpression\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUnaryExpression\fP (\fBstd::string\fP \fBop\fP, \fBExpression\fP *\fBrhs\fP=nullptr)"
.br
.ti -1c
.RI "void \fBaccept\fP (\fBVisitor\fP &visitor) const override"
.br
.ti -1c
.RI "const char * \fBtype\fP () const override"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstd::string\fP \fBop\fP"
.br
.ti -1c
.RI "\fBExpression\fP * \fBrhs\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UnaryExpression::UnaryExpression (\fBstd::string\fP op, \fBExpression\fP * rhs = \fCnullptr\fP)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void UnaryExpression::accept (\fBVisitor\fP & visitor) const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBNode\fP\&.
.SS "const char* UnaryExpression::type () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBNode\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBstd::string\fP UnaryExpression::op"

.SS "\fBExpression\fP* UnaryExpression::rhs"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
