.TH "src/util.h" 3 "Sun Apr 30 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/util.h
.SH SYNOPSIS
.br
.PP
\fC#include <unicode/uchar\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "const char * \fBu_charCategory\fP (int c)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "const char* u_charCategory (int c)"

.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
