.TH "VariableDeclaration" 3 "Sat Jun 10 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VariableDeclaration
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.PP
Inherits \fBExpression\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVariableDeclaration\fP (\fBIdentifier\fP *\fBidentifier\fP, \fBExpression\fP *\fBinitializer\fP=nullptr)"
.br
.ti -1c
.RI "void \fBaccept\fP (\fBVisitor\fP &visitor) const override"
.br
.ti -1c
.RI "const char * \fBtype\fP () const override"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBIdentifier\fP * \fBidentifier\fP"
.br
.ti -1c
.RI "\fBExpression\fP * \fBinitializer\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "VariableDeclaration::VariableDeclaration (\fBIdentifier\fP * identifier, \fBExpression\fP * initializer = \fCnullptr\fP)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void VariableDeclaration::accept (\fBVisitor\fP & visitor) const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBNode\fP\&.
.SS "const char* VariableDeclaration::type () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBNode\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBIdentifier\fP* VariableDeclaration::identifier"

.SS "\fBExpression\fP* VariableDeclaration::initializer"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
