.TH "src/visitor.cpp" 3 "Wed Jun 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/visitor.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'visitor\&.h'\fP
.br
\fC#include <memory>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBLambdaVisitor< Lambda >\fP"
.br
.ti -1c
.RI "struct \fBDelegateVistor\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
