.TH "src/visitor.h" 3 "Wed Jun 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/visitor.h
.SH SYNOPSIS
.br
.PP
\fC#include <memory>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBVisitor\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
