.TH "WithStatement" 3 "Sun May 14 2017" "ECMAScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WithStatement
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.PP
Inherits \fBStatement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWithStatement\fP (\fBExpression\fP *\fBobject\fP, \fBStatement\fP *\fBbody\fP)"
.br
.ti -1c
.RI "void \fBaccept\fP (\fBVisitor\fP &visitor) const override"
.br
.ti -1c
.RI "const char * \fBtype\fP () const override"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBExpression\fP * \fBobject\fP"
.br
.ti -1c
.RI "\fBStatement\fP * \fBbody\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "WithStatement::WithStatement (\fBExpression\fP * object, \fBStatement\fP * body)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void WithStatement::accept (\fBVisitor\fP & visitor) const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBNode\fP\&.
.SS "const char* WithStatement::type () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBNode\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBStatement\fP* WithStatement::body"

.SS "\fBExpression\fP* WithStatement::object"


.SH "Author"
.PP 
Generated automatically by Doxygen for ECMAScript from the source code\&.
