name: "Build"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-ubuntu-clang12:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - run: sudo apt-get install ninja-build
    - run: make ci preset=release-clang12

  build-windows-msvc:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - run: choco install ninja
    - run: make ci



  # build:
  #   strategy:
  #     matrix:
  #       os:
  #         - ubuntu-latest
  #         - windows-latest
  #         - macos-latest
  #   runs-on: ${{ matrix.os }}
  #   - if: matrix.os == 'windows-latest'
  #     name: Install windows dependencies
  #     run: choco install ninja
  #   - if: matrix.os == 'macos-latest'
  #     name: Install macos dependencies
  #     run: brew install ninja     
