name: "Build"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - windows-latest
          # - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install ninja-build
    - if: matrix.os == 'windows-latest'
      run: choco install ninja
    - if: matrix.os == 'macos-latest'
      run: brew install ninja     
    - name: configure
      run: make configure CXX=clang++
    - name: make
      run: make dump build
    - name: test
      run: make test