on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:

  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/vcpkg
        key: ${{ runner.os }}-vcpkg        
    - run: sudo apt-get install ninja-build lcov
    - run: make configure preset=debug CXX=g++-11 CXXFLAGS="--coverage"
    - run: make test-report preset=debug
    - uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: out/build/debug/lcov.info

  build-macos-clang13:
    runs-on: macos-latest
    needs:
      - test
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - run: brew install ninja
    - run: make configure CXX=clang++
    - run: make ci

  build-ubuntu-clang12:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/vcpkg
        key: ${{ runner.os }}-vcpkg
    - run: sudo apt-get install ninja-build
    - run: make configure CXX=clang++-12
    - run: make ci

  build-ubuntu-gcc10:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/vcpkg
        key: ${{ runner.os }}-vcpkg
    - run: sudo apt-get install ninja-build
    - run: make configure CXX=g++-10
    - run: make ci

  build-windows-msvc:
    runs-on: windows-latest
    needs:
      - test
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/vcpkg
        key: ${{ runner.os }}-vcpkg
    - uses: ilammy/msvc-dev-cmd@v1
    - run: choco install ninja
    - run: make configure CXX=cl
    - run: make ci

  build-windows-clang:
    runs-on: windows-latest
    needs:
      - test
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/vcpkg
        key: ${{ runner.os }}-vcpkg        
    - run: choco install ninja
    - run: make configure CXX=clang++
    - run: make ci
